lzc-sdk-version: "0.1"
name: OxiCloud
package: cloud.lazycat.app.oxicloud
version: 0.0.1
description: NextCloud 的轻量级替代品
homepage: https://github.com/DioCrafts/OxiCloud
author: DioCrafts
application:
  subdomain: oxicloud
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://oxicloud:8086/
services:
  postgres:
    image: docker.hlmirror.com/postgres:17.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oxicloud
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
      - /lzcapp/pkg/content:/docker-entrypoint-initdb.d/
    health_check:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
        
  oxicloud:
    image: docker.hlmirror.com/atareao/oxicloud:latest
    environment:
      - OXICLOUD_DB_CONNECTION_STRING=postgres://postgres:postgres@postgres/oxicloud
    depends_on:
      - postgres
    binds:
      - /lzcapp/var/storage:/app/storage
